module.exports.userSeeds = [
  {
    first_name: "Adam",
    last_name: "McPhee",
    username: "adam@gmail.com",
    tagline: "Looking for a good time",
    status: "inactive",
    profile_picture: "",
    photos: [],
    friends: [],
  },
  {
    first_name: "Torin",
    last_name: "Latarius",
    username: "torin@gmail.com",
    tagline: "Where's the party at",
    status: "inactive",
    profile_picture: "",
    photos: [],
    friends: [],
  },
  {
    first_name: "Alex",
    last_name: "Vidic",
    username: "alex@gmail.com",
    tagline: "Probably playing sports..",
    status: "inactive",
    profile_picture: "",
    photos: [],
    friends: [],
  },
  {
    first_name: "Josh",
    last_name: "Gomberoff",
    username: "josh@gmail.com",
    tagline: "Catch me if you can",
    status: "inactive",
    profile_picture: "",
    photos: [],
    friends: [],
  },
];
