module.exports.userSeeds = [
  {
    first_name: "Adam",
    last_name: "McPhee",
    username: "adam@gmail.com",
    tagline: "Looking for a good time",
    status: { updated: Date.now(), status: "Inactive" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    photos: [],
    friends: [],
    location: "Vancouver",
  },
  {
    first_name: "Torin",
    last_name: "Latarius",
    username: "torin@gmail.com",
    tagline: "Where's the party at",
    status: { updated: Date.now(), status: "Ready" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    photos: [],
    friends: [],
    location: "Vancouver",
  },
  {
    first_name: "Alex",
    last_name: "Vidic",
    username: "alex@gmail.com",
    tagline: "Probably playing sports..",
    status: { updated: Date.now(), status: "Searching" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    photos: [],
    friends: [],
    location: "Vancouver",
  },
  {
    first_name: "Josh",
    last_name: "Gomberoff",
    username: "josh@gmail.com",
    tagline: "Catch me if you can",
    status: { updated: Date.now(), status: "Busy" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    photos: [],
    friends: [],
    location: "Vancouver",
  },
  {
    first_name: "Ingrid",
    last_name: "Zwaiman",
    username: "ingrid@gmail.com",
    tagline: "Hope you like cold dips..!",
    status: { updated: Date.now(), status: "Ready" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    photos: [],
    friends: [],
    location: "Vancouver",
  },
];
