module.exports.userSeeds = [
  {
    first_name: "Adam",
    last_name: "McPhee",
    username: "adam@gmail.com",
    tagline: "Looking for a good time",
    status: { updated: Date.now(), status: "Ready" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    friends: [],
    location: "Vancouver, CA",
  },
  {
    first_name: "Torin",
    last_name: "Latarius",
    username: "torin@gmail.com",
    tagline: "Where's the party at",
    status: { updated: Date.now(), status: "Ready" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    friends: [],
    location: "Vancouver, CA",
  },
  {
    first_name: "Alex",
    last_name: "Vidic",
    username: "alex@gmail.com",
    tagline: "Probably playing sports..",
    status: { updated: Date.now(), status: "Busy" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    friends: [],
    location: "Vancouver, CA",
  },
  {
    first_name: "Josh",
    last_name: "Gomberoff",
    username: "josh@gmail.com",
    tagline: "Catch me if you can",
    status: { updated: Date.now(), status: "Busy" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    friends: [],
    location: "Vancouver, CA",
  },
  {
    first_name: "Ingrid",
    last_name: "Zwaiman",
    username: "ingrid@gmail.com",
    tagline: "Hope you like cold dips..!",
    status: { updated: Date.now(), status: "Ready" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    friends: [],
    location: "Vancouver, CA",
  },
];

module.exports.userSeeds2 = [
  {
    first_name: "Michael",
    last_name: "McCollar",
    username: "michael@gmail.com",
    tagline: "Engineering circuits yo",
    status: { updated: Date.now(), status: "Busy" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    friends: [],
    location: "Vancouver, CA",
  },
  {
    first_name: "Allie",
    last_name: "Lapin",
    username: "allie@gmail.com",
    tagline: "Hike all day, all night.",
    status: { updated: Date.now(), status: "Busy" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    friends: [],
    location: "Vancouver, CA",
  },
  {
    first_name: "Magnus",
    last_name: "Hvidsten",
    username: "magnus@gmail.com",
    tagline: "I promise we won't argue",
    status: { updated: Date.now(), status: "Ready" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    friends: [],
    location: "Vancouver, CA",
  },
  {
    first_name: "Marcus",
    last_name: "Nicholl",
    username: "marcus@gmail.com",
    tagline: "Music man and music machine",
    status: { updated: Date.now(), status: "Busy" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    friends: [],
    location: "Vancouver, CA",
  },
  {
    first_name: "Arthur",
    last_name: "Denefle",
    username: "arthur@gmail.com",
    tagline: "City pop or gtfo",
    status: { updated: Date.now(), status: "Ready" },
    flake: ((Math.random() * 100) % 5).toFixed(1),
    friends: [],
    location: "Vancouver, CA",
  },
];
